FROM node:14-alpine AS build
WORKDIR /app

ADD  . /app/

RUN yarn install
RUN yarn build:prod

FROM node:14-alpine AS run
WORKDIR /dspace-ui

COPY --from=build /app/dist /dspace-ui/dist
COPY --from=build /app/config/config.example.yml /dspace-ui/config/config.prod.yml

EXPOSE 4000
CMD [ "node", "./dist/server/main.js" ]